Fix for _MelNpcData TTT
Another "defaults" issue - granted ita was simpler to implement these
defaults, but not the correct approach

record_structs.pyc  198 dumpData: Error dumping data:
Traceback (most recent call last):
  File "bash\brec\record_structs.py", line 196, in dumpData
  File "bash\brec\advanced_elements.py", line 888, in dumpData
  File "bash\brec\basic_elements.py", line 182, in dumpData
  File "bash\brec\advanced_elements.py", line 524, in pack_subrecord_data
struct.error: pack expected 8 items for packing (got 22)

record_structs.pyc  199 dumpData: Occurred while dumping <[NPC_:2300865E]>
record_structs.pyc  209 dumpData: > dispositionBase: 0
record_structs.pyc  209 dumpData: > aggroRadiusBehavior: 0x00000000 (None)
record_structs.pyc  209 dumpData: > fatigue: 0
record_structs.pyc  209 dumpData: > items: []
record_structs.pyc  209 dumpData: > animations: []
record_structs.pyc  209 dumpData: > attributes: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
record_structs.pyc  209 dumpData: > responsibility: 50
record_structs.pyc  209 dumpData: > hairBlue: 0
record_structs.pyc  209 dumpData: > energyLevel: 50
record_structs.pyc  209 dumpData: > trainSkill: -1
record_structs.pyc  209 dumpData: > flags: 0x00000000 (None)
record_structs.pyc  209 dumpData: > skillOffsets: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
record_structs.pyc  209 dumpData: > confidence: 2
record_structs.pyc  209 dumpData: > level_offset: 1
record_structs.pyc  209 dumpData: > factions: []
record_structs.pyc  209 dumpData: > headParts: []
record_structs.pyc  209 dumpData: > aiPackages: []
record_structs.pyc  209 dumpData: > skillValues: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
record_structs.pyc  209 dumpData: > mood: 0
record_structs.pyc  209 dumpData: > calcMax: 0
record_structs.pyc  209 dumpData: > unused_aidt: b'\x00\x00\x00'
record_structs.pyc  209 dumpData: > calcMin: 0
record_structs.pyc  209 dumpData: > barterGold: 0
record_structs.pyc  209 dumpData: > trainLevel: 0
record_structs.pyc  209 dumpData: > aggression: 0
record_structs.pyc  209 dumpData: > hairGreen: 0
record_structs.pyc  209 dumpData: > hairLength: 0.6641171694063429
record_structs.pyc  209 dumpData: > hairRed: 0
record_structs.pyc  209 dumpData: > health: 0
record_structs.pyc  209 dumpData: > services: 0x00000000 (None)
record_structs.pyc  209 dumpData: > unused3: b'\x00'
record_structs.pyc  209 dumpData: > spells: []
record_structs.pyc  209 dumpData: > karma: Rounder(0.0)
record_structs.pyc  209 dumpData: > templateFlags: 0x00000000 (None)
record_structs.pyc  209 dumpData: > speedMultiplier: 0
record_structs.pyc  209 dumpData: > aggroRadius: 0
record_structs.pyc  209 dumpData: > assistance: 0
patcher_dialog.pyc  271 _error: Exception during Bashed Patch building:
Traceback (most recent call last):
  File "bash\basher\patcher_dialog.py", line 190, in PatchExecute
  File "bash\basher\patcher_dialog.py", line 280, in _save_pbash
  File "bash\mod_files.py", line 291, in safeSave
  File "bash\mod_files.py", line 323, in save
  File "bash\brec\record_groups.py", line 260, in dump
  File "bash\brec\record_groups.py", line 249, in getSize
  File "bash\brec\record_groups.py", line 250, in <genexpr>
  File "bash\brec\record_structs.py", line 489, in getSize
  File "bash\brec\record_structs.py", line 627, in dumpData
  File "bash\brec\record_structs.py", line 196, in dumpData
  File "bash\brec\advanced_elements.py", line 888, in dumpData
  File "bash\brec\basic_elements.py", line 182, in dumpData
  File "bash\brec\advanced_elements.py", line 524, in pack_subrecord_data
struct.error: pack expected 8 items for packing (got 22)


Now the default being used means that the _MelNpcData was not present?
In this case we should not be dumping it - part of dropping defaults
in 480 branch - but is this normal?