Manual py3 fixups RRR
Mopy/bash/basher/__init__.py:
Mopy/bash/bolt.py:
Drop OrderedDefaultDict
- Dicts are now ordered by default. Causes a layout conflict otherwise.

Mopy/Wrye Bash Launcher.pyw:
Drop UnicodeImporter hack
- Obsoleted on Python 3.

Mopy/bash/bash.py:
Don't decode sys.argv/sys.executable
- These are unicode on py3

Update bugdump handle creation for py3

Mopy/bash/localize.py:
Drop unicode parameter of gettext install
- The first WB error popup on Python 3 now shows :)

Catch OSError in format_date
- Py3 seems to throw that instead of ValueError.

Mopy/bash/bush.py:
Fix __import__ usage
- Needs 1 passed instead of -1 on py3. The game select dialog shows now!

Mopy/bash/bolt.py:
Handle implicit iteritems etc.
- I'll forgive 2to3 not catching these

Don't decode tempfile output
- Note I went a bit nuclear with Path.tempDir - in the words of Elsa,
  let it blow :P

Drop encode/decode logic around urllib.quote
- Handles unicode just fine on py3.

Mopy/bash/basher/patcher_dialog.py:
clock -> process_time
- Was removed in py3. Added it to our 2to3 fork.

Mopy/bash/basher/saves_links.py:
Fix cosave dumping not working on py3
- We'll probably run into this a whole bunch: py3 changes how
  bound/unbound methods work.

Mopy/bash/basher/gui_patchers.py:
Drop py2 compat hacks
- Gets Oblivion to boot.

Mopy/bash/archives.py:
Mopy/bash/bosh/bain.py:
Mopy/bash/bosh/omods.py:
Mopy/bash/env/linux.py:
Deal with all subprocess output

- On py3, we should pass an encoding parameter instead of bothering with
  manually decoding stuff.

Mopy/bash/env/windows.py:
Fix registry timestamp parsing on py3

The struct unpacking workaround is no longer required, QueryValueEx
returns an integer directly.

Mopy/bash/patcher/patchers/checkers.py:
Decode rec_type before appending to log

Could technically be done on py2 as well, but let's just stick it in the
py3 fixup commit. Less noise.

Mopy/bash/bosh/bsa_files.py:
Fix ord() being called on int

Even had a note for it :)

Mopy/bash/patcher/patchers/multitweak_settings.py:
Don't pass floats to int GMST tweaks

Otherwise blows up with a traceback:

Traceback (most recent call last):
  File "bash\brec\record_structs.py", line 198, in dumpData
  File "bash\brec\advanced_elements.py", line 883, in dumpData
  File "bash\brec\basic_elements.py", line 186, in dumpData
  File "bash\brec\basic_elements.py", line 236, in pack_subrecord_data
struct.error: required argument is not an integer

Py3 is a lot more strict about this, which is nice.

Mopy/bash/bosh/save_headers.py:
Fix time calculation in FO4

Would *love* to have PEP 467's iterbytes here, but at least that's
coming in Python 3.10.

Mopy/bash/patcher/patchers/mergers.py:
Do not sort MreLv* instances

No idea how this didn't blow up on py2, but these clearly should not be
sorted. They can't be compared, and there isn't even a reason to sort
them in the first place.

Fix leveled list patcher handling of None eids

Would blow up since you can't compare None to str objects on py3.

[Utumno]Fixups for parsers:

csv.reader is unicode now

Traceback (most recent call last):
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\balt.py", line 1771, in __Execute
    self.Execute()
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\mod_links.py", line 2285, in Execute
    editorIds.readFromText(textPath)
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\parsers.py", line 111, in readFromText
    with _CsvReader(csv_path) as ins:
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\parsers.py", line 63, in __init__
    delimiter = b';' if b';' in first_line else b','
TypeError: 'in <string>' requires string as left operand, not bytes

Now that all this (expensive) decode/encode machinery is not needed
_CsvReader last use was absorbed in readFromText.

Mopy/bash/basher/__init__.py:
Handle None in mouse_index

Can't compare it to an integer in py3:

Traceback (most recent call last):
  File "bash\gui\events.py", line 177, in _post
  File "bash\basher\__init__.py", line 374, in OnDClick
TypeError: '<' not supported between instances of 'NoneType' and 'int'

On py2, this instead evaluates to True, so the right solution is to
explicitly check for None.

Also renamed curr_name, that should be reserved for MasterInfo.

py3 in launcher from @ warmfrost RRR