Fix for None eid in ? records RRR did we get a bugdump since?
Bugdump missing

https://discord.com/channels/537706885965676554/537710082755133460/878233707633315901

Traceback (most recent call last):
  File "bash\gui\events.pyo", line 177, in _post
  File "bash\balt.pyo", line 825, in _conversation_wrapper
  File "bash\basher\patcher_dialog.pyo", line 177, in PatchExecute
  File "bash\patcher\patch_files.pyo", line 240, in scanLoadMods
  File "bash\patcher\base.pyo", line 81, in scan_mod_file
  File "bash\patcher\patchers\base.pyo", line 144, in scanModFile
  File "bash\patcher\patchers\multitweak_assorted.pyo", line 751, in wants_record
  File "bash\patcher\patchers\multitweak_assorted.pyo", line 729, in _is_nirnroot
  File "bash\patcher\patchers\multitweak_assorted.pyo", line 729, in <genexpr>
AttributeError: 'NoneType' object has no attribute 'lower'

Inf:
This seems like the right fix, it should ignore records without an EDID.
And nice walrus operator :P