Move building exe to pyinstaller RRR also move earlier in branch?
(see     Bump requirements/CI/Tests/version
 currently cb88b754f1e57d8b74f3aeb0f909d17daae6a98a)

Translation scripts are in the wrong(?) location. I guess some scripts
expect them to be in Mopy/bash/ but not sure how that interacts with
PyInstaller - needs further testing.

Infernio:

Update spec to exclude unnecessary binaries

Update spec to skip Tcl/Tk

Run PyInstaller as subprocess with -OO

Fix stdin usage in standalone builds

PyInstaller standalone builds do not have a console and therefore have
to sys.stdin.

ci: Re-enable building on py3

Drop MSVC download and inclusion in installer

Pass all std* parameters to Popen

If one of those three is passed, all three must be passed.
Otherwise it breaks on py3 standalones:

Traceback (most recent call last):
  File "bash\bash.py", line 258, in main
  File "bash\bash.py", line 424, in _main
  File "bash\barb.py", line 162, in backup_settings
  File "bash\barb.py", line 186, in _backup_settings
  File "bash\archives.py", line 54, in compress7z
  File "subprocess.py", line 829, in __init__
  File "subprocess.py", line 1288, in _get_handles
OSError: [WinError 6] The handle is invalid

Since PyInstaller 4.4, iter_modules is finally supported - dropped the
previous hack. Note that it seems to have some bugs, like giving us back
the __init__.py file while claiming ispkg=True - so work around that by
checking if it actually has the GAME_TYPE field.

Closes # 491 <--- RRR

Co-authored-by: Infernio <infernio@icloud.com>