WIP write_rows
The real gain here is getting rid of two patch game constants - goal is
to simplify game handling movng what belongs to the records there.
Consider the helper methods introduced transient - I am trying to
encapsulate the weird id_stored_data -

FFF writerow XXXXX _APraser broken (uses eid key)

Traceback (most recent call last):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\balt.py", line 1770, in __Execute
    self.Execute()
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\mod_links.py", line 1749, in Execute
    parser.write_text_file(textPath)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\parsers.py", line 78, in write_text_file
    self._write_rows(out)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\parsers.py", line 147, in _write_rows
    for lfid, stored_data in _key_sort(id_data, **self._sort_args):
ValueError: too many values to unpack (expected 2)

FFF fixup for parent

@@ -52,3 +52,3 @@ def _key_sort(di, id_eid_=None, keys_dex=(), values_key=u'', by_value=False):
         for k in sorted(di, key=key_f):
-            yield k, di[k], id_eid_[k]
+            yield k, (di[k], id_eid_[k])
     else:
@@ -485,8 +485,8 @@ def _parse_line(self, csv_fields):

morphName

WIP parse_line XXX

ActorLevels WIP EEE

self.mod_id_levels -> self.id_stored_data FFF XXX

SSS preservers add next TTT

- self.id_exhaustion does not seem useful?

FFF _nested_type

Bye bush.game.relations_csv_header

Bye bush.game.relations_csv_row_format SSS

Where attr_csv_struct[a][2] is put to use