TTT release mouse traceback on hitting restart
Traceback (most recent call last):
  File "/Users/ubik-mac13/Dropbox (Personal)/eclipse_workspaces/python/wrye-bash/Mopy/bash/bash.py", line 273, in main
    _main(opts, wx_locale)
  File "/Users/ubik-mac13/Dropbox (Personal)/eclipse_workspaces/python/wrye-bash/Mopy/bash/bash.py", line 452, in _main
    app.MainLoop()
  File "/Users/ubik-mac13/Dropbox (Personal)/eclipse_workspaces/python/wrye-bash/venv/venv/lib/python3.9/site-packages/wx/core.py", line 2237, in MainLoop
    rv = wx.PyApp.MainLoop(self)
wx._core.wxAssertionError: C++ assertion "!wxMouseCapture::IsInCaptureStack(this)" failed at /Users/robind/projects/bb2/dist-osx-py39/build/ext/wxWidgets/src/common/wincmn.cpp(453) in ~wxWindowBase(): Destroying window before releasing mouse capture: this will result in a crash later.

Turns out it's the balt.DnDStatusBar.OnDragEnd (duh) - on calling
event.Skip() - dragging started when user clicks on  restart button  -
then when destroying the Status bar realizes  mouse was never released.
Made it always release the mouse if captured TTT