Never skip the buildPatch phase
Otherwise the BP for Oblivion can crash because we may disable patchers
during the BP process (e.g. if they find they have nothing to patch).
buildPatch also handles the masters assignment, so if we forward MGEFs
(which is necessary in Oblivion), we may end up with missing masters and
hence get tracebacks like this while saving the BP:

Traceback (most recent call last):
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\gui\events.py", line 178, in _post
    result = listener(*listener_args)
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\balt.py", line 809, in _conversation_wrapper
    return func(*args, **kwargs)
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\basher\patcher_dialog.py", line 186, in PatchExecute
    self._save_pbash(patchFile, patch_name)
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\basher\patcher_dialog.py", line 276, in _save_pbash
    patchFile.safeSave()
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\mod_files.py", line 290, in safeSave
    self.save(filePath.temp)
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\mod_files.py", line 303, in save
    self._convert_fids(to_long=False)
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\mod_files.py", line 370, in _convert_fids
    target_top.convertFids(mapper, to_long)
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\brec\record_groups.py", line 284, in convertFids
    record.convertFids(mapper,toLong)
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\brec\record_structs.py", line 636, in convertFids
    self.__class__.melSet.convertFids(self,mapper,toLong)
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\brec\record_structs.py", line 221, in convertFids
    record.fid = mapper(record.fid)
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\mod_files.py", line 362, in mapper
    return (_master_index(modName, object_id) << 24) | object_id
  File "E:\Infernio\Desktop\Programming\wrye-bash\Mopy\bash\mod_files.py", line 357, in _master_index
    return indices[m_name] if obj_id >= 0x800 else 0
KeyError: bolt.Path('Av Latta Magicka.esm')