[!]More py3 comments:
Mopy/bash/bosh/_saves.py: ! cause I just followed instructions :P - same
with bolt. Also that bunch of nonlocal in bain raises some style
questions - renamed couple of isdir.

Mopy/bash/load_order.py: added some monkey patching - I'd need the
BashLoadOrders that blew to see if all this is needed:

https://discord.com/channels/537706885965676554/537710082755133460/916155386841665576

localize.pyc  115 setup_locale: Set wxPython language to 'en_US'
localize.pyc  117 setup_locale: Set Wrye Bash language to 'en_US'
doc_viewer.pyc   38 <module>: pdfviewer using PyMuPDF (GPL)
bash.pyc  246 dump_environment: Using Wrye Bash Version 310.202111240909 (Standalone)
bash.pyc  246 dump_environment: OS info: Windows-10-10.0.19043-SP0, running on Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
bash.pyc  246 dump_environment: Python version: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
bash.pyc  246 dump_environment: Dependency versions:
bash.pyc  246 dump_environment:  - chardet: 4.0.0
bash.pyc  246 dump_environment:  - PyMuPDF: 1.19.1; bundled MuPDF version: 1.19.0
bash.pyc  246 dump_environment:  - python-lz4: 3.1.3; bundled LZ4 version: 1.9.3
bash.pyc  246 dump_environment:  - PyYAML: 6.0
bash.pyc  246 dump_environment:  - wxPython: 4.1.1 msw (phoenix) wxWidgets 3.1.5
bash.pyc  246 dump_environment: Input encoding: None; output encoding: utf-8
bash.pyc  246 dump_environment: Filesystem encoding: utf-8
bash.pyc  246 dump_environment: Command line: ['D:\\SteamLibrary\\steamapps\\common\\Skyrim Special Edition\\Mopy\\Wrye Bash.exe', '-d']
bash.pyc  491 _import_bush_and_set_game: Searching for game to manage:
bush.pyc  118 _supportedGames: The following games are supported by this version of Wrye Bash:
bush.pyc  121 _supportedGames:  Enderal, Enderal Special Edition, Fallout 3, Fallout 3 (WS), Fallout
bush.pyc  121 _supportedGames:  4, Fallout 4 (WS), Fallout 4 VR, Fallout New Vegas, Fallout New Vegas
bush.pyc  121 _supportedGames:  (WS), Morrowind, Morrowind (WS), Nehrim, Oblivion, Oblivion (WS),
bush.pyc  121 _supportedGames:  Skyrim, Skyrim Special Edition, Skyrim Special Edition (WS), Skyrim VR
bush.pyc  123 _supportedGames: Wrye Bash looked for games in the following places:
bush.pyc  124 _supportedGames:  1. Windows Registry:
bush.pyc  126 _supportedGames:   The following installed games were found via the registry:
bush.pyc   66 _print_found_games:  - Skyrim Special Edition: D:\SteamLibrary\steamapps\common\Skyrim Special Edition
bush.pyc  135 _supportedGames:   Make sure to run the launcher of each game you installed through Steam
bush.pyc  135 _supportedGames:   once, otherwise Wrye Bash will not be able to find it.
bush.pyc  136 _supportedGames:  2. Windows Store:
bush.pyc  142 _supportedGames:   No installed games with modding enabled were found via the Windows Store.
bush.pyc  147 _supportedGames:   Make sure to enable mods for each Windows Store game you have
bush.pyc  147 _supportedGames:   installed, otherwise Wrye Bash will not be able to find it.
bush.pyc  209 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.pyc  215 _detectGames: Set game mode to Skyrim Special Edition found in parent directory of Mopy:  D:\SteamLibrary\steamapps\common\Skyrim Special Edition
bush.pyc  231 __setGame: Using Skyrim Special Edition game: D:\SteamLibrary\steamapps\common\Skyrim Special Edition
initialization.pyc  158 init_dirs: My Games location set to C:\Users\alecr\Documents\My Games\Skyrim Special Edition
initialization.pyc  171 init_dirs: LocalAppData location set to C:\Users\alecr\AppData\Local\Skyrim Special Edition
initialization.pyc  219 init_dirs: Game Mods location set to D:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods
initialization.pyc  224 init_dirs: Bash Mod Data location set to D:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Mod Data
initialization.pyc  228 init_dirs: Installers location set to D:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Installers
initialization.pyc  230 init_dirs: Installers bash data location set to D:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bash
initialization.pyc  238 init_dirs: Checking if WB directories exist and creating them if needed:
initialization.pyc  242 init_dirs:  - D:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Mod Data
initialization.pyc  242 init_dirs:  - D:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Installers
initialization.pyc  242 init_dirs:  - D:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bain Converters
initialization.pyc  242 init_dirs:  - D:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bain Converters\--Duplicates
initialization.pyc  242 init_dirs:  - D:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bain Converters\--Corrupt
initialization.pyc  242 init_dirs:  - D:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bash
initialization.pyc  242 init_dirs:  - D:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bash\BSA Cache
loot_parser.pyc   48 <module>: Using LibYAML-based parser
loot_parser.pyc   83 __init__: Using these LOOT paths:
loot_parser.pyc   84 __init__:  Masterlist: C:\Users\alecr\AppData\Local\LOOT\Skyrim Special Edition\masterlist.yaml
loot_parser.pyc   85 __init__:  Userlist: C:\Users\alecr\AppData\Local\LOOT\Skyrim Special Edition\userlist.yaml
loot_parser.pyc   86 __init__:  Taglist (fallback): D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\taglists\SkyrimSE\taglist.yaml
__init__.pyc 3608 initBosh: Initialized loot_parser, compatible with libloot v0.16.x
__init__.pyc 3611 initBosh: Looking for main game INI at C:\Users\alecr\Documents\My Games\Skyrim Special Edition\Skyrim.ini
windows.pyc  967 testUAC: Testing if game folder is UAC-protected
barb.pyc  158 backup_settings:
barb.pyc  159 backup_settings: BACKUP BASH SETTINGS: C:\Users\alecr\Desktop\Backup Bash Settings Skyrim Special Edition (2021-12-02 20.15.56) v307-310.202111240909.7z
barb.pyc  171 _backup_settings: Skyrim Special Edition Mods\Bash Mod Data\Table.dat.bak <-- D:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Mod Data\Table.dat.bak
barb.pyc  171 _backup_settings: Skyrim Special Edition Mods\Bash Mod Data\Table.dat <-- D:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Mod Data\Table.dat
barb.pyc  171 _backup_settings: My Games\Skyrim Special Edition\BashLoadOrders.dat.bak <-- C:\Users\alecr\Documents\My Games\Skyrim Special Edition\BashLoadOrders.dat.bak
barb.pyc  171 _backup_settings: My Games\Skyrim Special Edition\BashSettings.dat.bak <-- C:\Users\alecr\Documents\My Games\Skyrim Special Edition\BashSettings.dat.bak
barb.pyc  171 _backup_settings: My Games\Skyrim Special Edition\BashSettings.dat <-- C:\Users\alecr\Documents\My Games\Skyrim Special Edition\BashSettings.dat
barb.pyc  171 _backup_settings: My Games\Skyrim Special Edition\BashLoadOrders.dat <-- C:\Users\alecr\Documents\My Games\Skyrim Special Edition\BashLoadOrders.dat
barb.pyc  171 _backup_settings: Skyrim Special Edition\Mopy\bash\l10n\de_DE.po <-- D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\l10n\de_DE.po
barb.pyc  171 _backup_settings: Skyrim Special Edition\Mopy\bash\l10n\it_IT.po <-- D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\l10n\it_IT.po
barb.pyc  171 _backup_settings: Skyrim Special Edition\Mopy\bash\l10n\ja_JP.po <-- D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\l10n\ja_JP.po
barb.pyc  171 _backup_settings: Skyrim Special Edition\Mopy\bash\l10n\pt_PT.po <-- D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\l10n\pt_PT.po
barb.pyc  171 _backup_settings: Skyrim Special Edition\Mopy\bash\l10n\ru_RU.po <-- D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\l10n\ru_RU.po
barb.pyc  171 _backup_settings: Skyrim Special Edition\Mopy\bash\l10n\zh_CN.po <-- D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\l10n\zh_CN.po
barb.pyc  171 _backup_settings: Skyrim Special Edition\Mopy\bash\l10n\zh_TW.po <-- D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\bash\l10n\zh_TW.po
barb.pyc  171 _backup_settings: Skyrim Special Edition\Data\BashTags\Unofficial Skyrim Special Edition Patch.txt <-- D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\BashTags\Unofficial Skyrim Special Edition Patch.txt
barb.pyc  171 _backup_settings: Skyrim Special Edition\Data\BashTags\__folder_managed_by_vortex <-- D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\BashTags\__folder_managed_by_vortex
__init__.pyc 1529 _initDB: Initializing BSAInfos
__init__.pyc 1530 _initDB:  store_dir: D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data
__init__.pyc 1531 _initDB:  bash_dir: D:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Mod Data\BSA Data
__init__.pyc 1529 _initDB: Initializing ModInfos
__init__.pyc 1530 _initDB:  store_dir: D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data
__init__.pyc 1531 _initDB:  bash_dir: D:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Mod Data
_games_lo.pyc  663 print_lo_paths: Using the following load order files:
_games_lo.pyc  665 print_lo_paths:  - Load order and active plugins: C:\Users\alecr\AppData\Local\Skyrim Special Edition\plugins.txt
Wrye Bash encountered an error.
Please post the information below to the official thread at
https://afkmods.com/index.php?/topic/4966-wrye-bash-all-games
or to the Wrye Bash Discord at
https://discord.gg/NwWvAFR

Traceback (most recent call last):
  File "bash\bash.py", line 287, in main
  File "bash\bash.py", line 454, in _main
  File "bash\basher\__init__.py", line 4210, in Init
  File "bash\basher\__init__.py", line 4237, in InitData
  File "bash\bosh\__init__.py", line 2069, in __init__
  File "bash\load_order.py", line 94, in initialize_load_order_handle
  File "bash\load_order.py", line 373, in __load_pickled_load_orders
  File "bash\bolt.py", line 1362, in load
  File "bash\bolt.py", line 1341, in _perform_load
  File "bash\load_order.py", line 145, in __setstate__
AttributeError: 'LoadOrder' object has no attribute '_activeOrdered'